PREFIX svc: <http://www.mygrid.org.uk/mygrid-moby-service#>
PREFIX dc: <http://protege.stanford.edu/plugins/owl/dc/protege-dc.owl#>

PREFIX moby: <http://moby/>


MODIFY GRAPH <http://mobyreg/services/>
DELETE
{
  ?inputparam svc:hasDefaultValue ?default .
}
INSERT
{
  ?inputparam svc:hasDefaultValue "1000" .
}
WHERE 
{ 
  ?service svc:hasServiceNameText "MOBYSHoundGiFromGOID" .
 
  # Some web services perform more than one type of operation.
  # Moby services never do, though.

  ?service svc:hasOperation ?operation .

  ?operation svc:inputParameter ?inputparam .
  ?inputparam svc:hasParameterNameText "cutoff" .

  ?inputparam svc:hasDefaultValue ?default .
 
}
